#!/usr/bin/bash

SHARDS_ROOT_DIR="output/wiki_en/shards/shards_1627"
data_cache_dir="data/wiki_en/cache"
joblib_temp_folder="tmp"
src_lang="eng_Latn"
tgt_lang="hin_Deva"
num_procs_for_data_ops=64
batch_size=512
devices_for_translation="0,1,2,3,4,5,6,7"

run_translation() {

    shard_dir=$1

    HF_DATASETS_CACHE=tmp python setu-translate/stages/binarize.py \
        --root_dir "$PWD" \
        --data_files "${shard_dir}/sentences/*.arrow" \
        --cache_dir $data_cache_dir \
        --binarized_dir "${shard_dir}/${tgt_lang}/binarized_sentences" \
        --joblib_temp_folder $joblib_temp_folder \
        --batch_size $batch_size \
        --total_procs $num_procs_for_data_ops \
        --run_joblib False \
        --src_lang $src_lang \
        --tgt_lang $tgt_lang

    HF_DATASETS_CACHE=tmp python setu-translate/stages/tlt_pipelines/translate_joblib.py \
        --root_dir "$PWD" \
        --data_files "${shard_dir}/${tgt_lang}/binarized_sentences/*.arrow" \
        --cache_dir $data_cache_dir \
        --base_save_dir "${shard_dir}/${tgt_lang}/model_out" \
        --joblib_temp_folder $joblib_temp_folder \
        --batch_size $batch_size \
        --total_procs $num_procs_for_data_ops \
        --devices $devices_for_translation

}

# Glob the directory and get all shards
for SHARD_DIR in "$SHARDS_ROOT_DIR"/*; do
    # Check if it's a directory
    if [ -d "$SHARD_DIR" ]; then
        echo "Translating shard sub-folder: $SHARD_DIR"

        run_translation $SHARD_DIR
    fi
done